import { Device } from "./types";

export const MOCK_DEVICES: Device[] = [
  {
    id: "CAB-RYD-001",
    internalId: 1,
    type: "cabinet",
    name: "Cabinet Riyadh 1",
    location: "Al-Olaya – King Fahd Road",
    city: "Riyadh",
    status: "active",
    slots: 20,
    availableSlots: 14,
    createdAt: new Date().toISOString(),
    firmware: "v2.3.8",
    lastHeartbeat: "30s ago",
    todayOps: 42,
    uptime: 99.8,
  },
  {
    id: "CAB-RYD-002",
    internalId: 2,
    type: "cabinet",
    name: "Cabinet Riyadh 2",
    location: "Al-Malaz – Salah Al-Din St.",
    city: "Riyadh",
    status: "inactive",
    slots: 20,
    availableSlots: 0,
    createdAt: new Date().toISOString(),
    firmware: "v2.3.5",
    lastHeartbeat: "45 min ago",
    todayOps: 18,
    uptime: 94.2,
  },
  {
    id: "CAB-RYD-003",
    internalId: 3,
    type: "cabinet",
    name: "Cabinet Riyadh 3",
    location: "Al-Nakheel – Anas Bin Malik Rd.",
    city: "Riyadh",
    status: "active",
    slots: 20,
    availableSlots: 11,
    createdAt: new Date().toISOString(),
    firmware: "v2.3.8",
    lastHeartbeat: "15s ago",
    todayOps: 35,
    uptime: 99.9,
  },
  {
    id: "CHG-RYD-001",
    internalId: 4,
    type: "charging",
    name: "Charger Riyadh 1",
    location: "Al-Sulaimaniyah – Takhasussi St.",
    city: "Riyadh",
    status: "active",
    slots: 4,
    availableSlots: 4,
    createdAt: new Date().toISOString(),
    firmware: "v1.8.2",
    lastHeartbeat: "10s ago",
    todayOps: 22,
    uptime: 99.5,
  },
  {
    id: "CHG-JED-001",
    internalId: 5,
    type: "charging",
    name: "Charger Jeddah 1",
    location: "Al-Hamra – Prince Sultan Rd.",
    city: "Jeddah",
    status: "maintenance",
    slots: 4,
    availableSlots: 0,
    createdAt: new Date().toISOString(),
    firmware: "v1.7.9",
    lastHeartbeat: "offline",
    todayOps: 0,
    uptime: 89.1,
  },
  {
    id: "CAB-JED-001",
    internalId: 6,
    type: "cabinet",
    name: "Cabinet Jeddah 1",
    location: "Al-Safa – Palestine St.",
    city: "Jeddah",
    status: "active",
    slots: 20,
    availableSlots: 9,
    createdAt: new Date().toISOString(),
    firmware: "v2.3.8",
    lastHeartbeat: "5s ago",
    todayOps: 28,
    uptime: 99.6,
  },
  {
    id: "CAB-DMM-001",
    internalId: 7,
    type: "cabinet",
    name: "Cabinet Dammam 1",
    location: "Al-Corniche – King Faisal Rd.",
    city: "Dammam",
    status: "active",
    slots: 20,
    availableSlots: 16,
    createdAt: new Date().toISOString(),
    firmware: "v2.3.8",
    lastHeartbeat: "20s ago",
    todayOps: 15,
    uptime: 99.9,
  },
  {
    id: "CHG-DMM-001",
    internalId: 8,
    type: "charging",
    name: "Charger Dammam 1",
    location: "Al-Shati – Prince Mohammed Rd.",
    city: "Dammam",
    status: "active",
    slots: 4,
    availableSlots: 2,
    createdAt: new Date().toISOString(),
    firmware: "v1.8.2",
    lastHeartbeat: "8s ago",
    todayOps: 19,
    uptime: 98.7,
  },
  {
    id: "CAB-MED-001",
    internalId: 9,
    type: "cabinet",
    name: "Cabinet Medina 1",
    location: "Al-Rawda – King Abdulaziz Rd.",
    city: "Medina",
    status: "active",
    slots: 20,
    availableSlots: 7,
    createdAt: new Date().toISOString(),
    firmware: "v2.3.8",
    lastHeartbeat: "12s ago",
    todayOps: 31,
    uptime: 99.4,
  },
  {
    id: "CHG-MED-001",
    internalId: 10,
    type: "charging",
    name: "Charger Medina 1",
    location: "Al-Aziziyah – Hira St.",
    city: "Medina",
    status: "maintenance",
    slots: 4,
    availableSlots: 0,
    createdAt: new Date().toISOString(),
    firmware: "v1.7.9",
    lastHeartbeat: "offline",
    todayOps: 0,
    uptime: 91.3,
  },
];